


export default {
  THEME_CHANGE:"THEME_CHANGE",
  THEME_INIT:"THEME_INIT",
  // 最热页面三个类型的action
  POPULAR_REFRESH:"POPULAR_REFRESH",
  POPULAR_LOAD_FAIL:'LOAD_POPULAR_FAIL',
  POPULAR_LOAD_SUCCESS:'LOAD_POPULAR_SUCCESS',
  // 最热页面的加载更多的两个action
  POPULAR_LOAD_MORE_SUCCESS:'POPULAR_LOAD_MORE_SUCCESS',
  POPULAR_LOAD_MORE_FAIL:'POPULAR_LOAD_MORE_FAIL'
} 