


export default {
  THEME_CHANGE:"THEME_CHANGE",
  THEME_INIT:"THEME_INIT",
  // 最热页面三个类型的action
  POPULAR_REFRESH:"POPULAR_REFRESH",
  LOAD_POPULAR_FAIL:'LOAD_POPULAR_FAIL',
  LOAD_POPULAR_SUCCESS:'LOAD_POPULAR_SUCCESS',

} 